describe(tt.getModuleSuiteName(), function() {
	describe('ReadGuildMemberBuildings', function() {
		it('Blood Lilies', async function() {
			const CityEntities = {
				"W_MultiAge_WILD24G1": {
					"id": "W_MultiAge_WILD24G1", "asset_id": "W_MultiAge_WILD24G1", "name": "Blood Lilies", "entity_levels": [], "abilities": [ { "gridId": "main", "__class__": "BuildingPlacementAbility" } ],
					"components": {
						"AllAge": {
							"placement": { "type": "placement", "gridId": "main", "content": "main", "size": { "type": "size", "x": 1, "y": 1, "z": 2, "__class__": "SizeComponent" }, "__class__": "PlacementComponent" },
							"constructionTime": { "type": "constructionTime", "time": 5, "__class__": "ConstructionTimeComponent" },
							"streetConnectionRequirement": { "type": "streetConnectionRequirement", "requiredLevel": 1, "__class__": "StreetConnectionRequirementComponent" },
							"rankingPoints": { "type": "rankingPoints", "typeFactor": 1, "specialFactor": 2, "__class__": "RankingPointsComponent" },
							"flags": { "type": "flags", "flags": 19, "__class__": "FlagsComponent" },
							"socialInteraction": { "type": "socialInteraction", "interactionType": "motivate", "__class__": "SocialInteractionComponent" },
							"tags": { "type": "tags", "tags": [ { "tag": "buildingType", "buildingType": "residential", "__class__": "BuildingTypeTag" } ], "__class__": "TagsComponent" },
							"value": { "type": "value", "rarity": "epic", "premiumEquivalent": 350, "__class__": "ValueComponent" },
							"autoPolivatePriority": { "type": "autoPolivatePriority", "priority": 100, "__class__": "AutoPolivatePriorityComponent" },
							"production": { "type": "production", "options": [ { "asset": "bazaar_5", "name": "Option 1", "time": 86400, "products": [
								{ "type": "resources", "playerResources": { "resources": { "strategy_points": 2 }, "__class__": "Resources" }, "__class__": "ResourceProduct" },
								{ "type": "guildResources", "onlyWhenMotivated": true, "guildResources": { "resources": { "all_goods_of_age": 5 }, "__class__": "Resources" }, "__class__": "GuildResourceProduct" }
							], "__class__": "ProductionOption" } ],
							"autoStart": true, "__class__": "ProductionsComponent" }
						},
						"BronzeAge": { "staticResources": { "type": "staticResources", "resources": { "resources": { "population": 20 }, "__class__": "Resources" }, "__class__": "StaticResourcesComponent" }, "happiness": { "type": "happiness", "demanded": 20, "__class__": "HappinessComponent" }, "boosts": { "type": "boosts", "boosts": [ { "type": "att_boost_attacker", "value": 1, "targetedFeature": "all", "__class__": "BoostHint" }, { "type": "att_boost_attacker", "value": 2, "targetedFeature": "battleground", "__class__": "BoostHint" }, { "type": "def_boost_attacker", "value": 2, "targetedFeature": "all", "__class__": "BoostHint" }, { "type": "def_boost_attacker", "value": 2, "targetedFeature": "battleground", "__class__": "BoostHint" } ], "__class__": "BoostsComponent" } },
						"IronAge": { "staticResources": { "type": "staticResources", "resources": { "resources": { "population": 50 }, "__class__": "Resources" }, "__class__": "StaticResourcesComponent" }, "happiness": { "type": "happiness", "demanded": 50, "__class__": "HappinessComponent" }, "boosts": { "type": "boosts", "boosts": [ { "type": "att_boost_attacker", "value": 1, "targetedFeature": "all", "__class__": "BoostHint" }, { "type": "att_boost_attacker", "value": 2, "targetedFeature": "battleground", "__class__": "BoostHint" }, { "type": "def_boost_attacker", "value": 2, "targetedFeature": "all", "__class__": "BoostHint" }, { "type": "def_boost_attacker", "value": 2, "targetedFeature": "battleground", "__class__": "BoostHint" } ], "__class__": "BoostsComponent" } },
						"EarlyMiddleAge": { "staticResources": { "type": "staticResources", "resources": { "resources": { "population": 80 }, "__class__": "Resources" }, "__class__": "StaticResourcesComponent" }, "happiness": { "type": "happiness", "demanded": 80, "__class__": "HappinessComponent" }, "boosts": { "type": "boosts", "boosts": [ { "type": "att_boost_attacker", "value": 1, "targetedFeature": "all", "__class__": "BoostHint" }, { "type": "att_boost_attacker", "value": 2, "targetedFeature": "battleground", "__class__": "BoostHint" }, { "type": "def_boost_attacker", "value": 2, "targetedFeature": "all", "__class__": "BoostHint" }, { "type": "def_boost_attacker", "value": 2, "targetedFeature": "battleground", "__class__": "BoostHint" } ], "__class__": "BoostsComponent" } },
						"HighMiddleAge": { "staticResources": { "type": "staticResources", "resources": { "resources": { "population": 110 }, "__class__": "Resources" }, "__class__": "StaticResourcesComponent" }, "happiness": { "type": "happiness", "demanded": 110, "__class__": "HappinessComponent" }, "boosts": { "type": "boosts", "boosts": [ { "type": "att_boost_attacker", "value": 1, "targetedFeature": "all", "__class__": "BoostHint" }, { "type": "att_boost_attacker", "value": 2, "targetedFeature": "battleground", "__class__": "BoostHint" }, { "type": "def_boost_attacker", "value": 2, "targetedFeature": "all", "__class__": "BoostHint" }, { "type": "def_boost_attacker", "value": 2, "targetedFeature": "battleground", "__class__": "BoostHint" } ], "__class__": "BoostsComponent" } },
						"LateMiddleAge": { "staticResources": { "type": "staticResources", "resources": { "resources": { "population": 150 }, "__class__": "Resources" }, "__class__": "StaticResourcesComponent" }, "happiness": { "type": "happiness", "demanded": 150, "__class__": "HappinessComponent" }, "boosts": { "type": "boosts", "boosts": [ { "type": "att_boost_attacker", "value": 1, "targetedFeature": "all", "__class__": "BoostHint" }, { "type": "att_boost_attacker", "value": 2, "targetedFeature": "battleground", "__class__": "BoostHint" }, { "type": "def_boost_attacker", "value": 2, "targetedFeature": "all", "__class__": "BoostHint" }, { "type": "def_boost_attacker", "value": 2, "targetedFeature": "battleground", "__class__": "BoostHint" } ], "__class__": "BoostsComponent" } },
						"ColonialAge": { "staticResources": { "type": "staticResources", "resources": { "resources": { "population": 180 }, "__class__": "Resources" }, "__class__": "StaticResourcesComponent" }, "happiness": { "type": "happiness", "demanded": 180, "__class__": "HappinessComponent" }, "boosts": { "type": "boosts", "boosts": [ { "type": "att_boost_attacker", "value": 1, "targetedFeature": "all", "__class__": "BoostHint" }, { "type": "att_boost_attacker", "value": 2, "targetedFeature": "battleground", "__class__": "BoostHint" }, { "type": "def_boost_attacker", "value": 2, "targetedFeature": "all", "__class__": "BoostHint" }, { "type": "def_boost_attacker", "value": 2, "targetedFeature": "battleground", "__class__": "BoostHint" } ], "__class__": "BoostsComponent" } },
						"IndustrialAge": { "staticResources": { "type": "staticResources", "resources": { "resources": { "population": 230 }, "__class__": "Resources" }, "__class__": "StaticResourcesComponent" }, "happiness": { "type": "happiness", "demanded": 230, "__class__": "HappinessComponent" }, "boosts": { "type": "boosts", "boosts": [ { "type": "att_boost_attacker", "value": 1, "targetedFeature": "all", "__class__": "BoostHint" }, { "type": "att_boost_attacker", "value": 2, "targetedFeature": "battleground", "__class__": "BoostHint" }, { "type": "def_boost_attacker", "value": 2, "targetedFeature": "all", "__class__": "BoostHint" }, { "type": "def_boost_attacker", "value": 2, "targetedFeature": "battleground", "__class__": "BoostHint" } ], "__class__": "BoostsComponent" } },
						"ProgressiveEra": { "staticResources": { "type": "staticResources", "resources": { "resources": { "population": 270 }, "__class__": "Resources" }, "__class__": "StaticResourcesComponent" }, "happiness": { "type": "happiness", "demanded": 270, "__class__": "HappinessComponent" }, "boosts": { "type": "boosts", "boosts": [ { "type": "att_boost_attacker", "value": 1, "targetedFeature": "all", "__class__": "BoostHint" }, { "type": "att_boost_attacker", "value": 2, "targetedFeature": "battleground", "__class__": "BoostHint" }, { "type": "def_boost_attacker", "value": 2, "targetedFeature": "all", "__class__": "BoostHint" }, { "type": "def_boost_attacker", "value": 2, "targetedFeature": "battleground", "__class__": "BoostHint" } ], "__class__": "BoostsComponent" } },
						"ModernEra": { "staticResources": { "type": "staticResources", "resources": { "resources": { "population": 320 }, "__class__": "Resources" }, "__class__": "StaticResourcesComponent" }, "happiness": { "type": "happiness", "demanded": 320, "__class__": "HappinessComponent" }, "boosts": { "type": "boosts", "boosts": [ { "type": "att_boost_attacker", "value": 1, "targetedFeature": "all", "__class__": "BoostHint" }, { "type": "att_boost_attacker", "value": 2, "targetedFeature": "battleground", "__class__": "BoostHint" }, { "type": "def_boost_attacker", "value": 2, "targetedFeature": "all", "__class__": "BoostHint" }, { "type": "def_boost_attacker", "value": 2, "targetedFeature": "battleground", "__class__": "BoostHint" } ], "__class__": "BoostsComponent" } },
						"PostModernEra": { "staticResources": { "type": "staticResources", "resources": { "resources": { "population": 360 }, "__class__": "Resources" }, "__class__": "StaticResourcesComponent" }, "happiness": { "type": "happiness", "demanded": 360, "__class__": "HappinessComponent" }, "boosts": { "type": "boosts", "boosts": [ { "type": "att_boost_attacker", "value": 1, "targetedFeature": "all", "__class__": "BoostHint" }, { "type": "att_boost_attacker", "value": 2, "targetedFeature": "battleground", "__class__": "BoostHint" }, { "type": "def_boost_attacker", "value": 2, "targetedFeature": "all", "__class__": "BoostHint" }, { "type": "def_boost_attacker", "value": 2, "targetedFeature": "battleground", "__class__": "BoostHint" } ], "__class__": "BoostsComponent" } },
						"ContemporaryEra": { "staticResources": { "type": "staticResources", "resources": { "resources": { "population": 410 }, "__class__": "Resources" }, "__class__": "StaticResourcesComponent" }, "happiness": { "type": "happiness", "demanded": 410, "__class__": "HappinessComponent" }, "boosts": { "type": "boosts", "boosts": [ { "type": "att_boost_attacker", "value": 1, "targetedFeature": "all", "__class__": "BoostHint" }, { "type": "att_boost_attacker", "value": 2, "targetedFeature": "battleground", "__class__": "BoostHint" }, { "type": "def_boost_attacker", "value": 2, "targetedFeature": "all", "__class__": "BoostHint" }, { "type": "def_boost_attacker", "value": 2, "targetedFeature": "battleground", "__class__": "BoostHint" } ], "__class__": "BoostsComponent" } },
						"TomorrowEra": { "staticResources": { "type": "staticResources", "resources": { "resources": { "population": 470 }, "__class__": "Resources" }, "__class__": "StaticResourcesComponent" }, "happiness": { "type": "happiness", "demanded": 470, "__class__": "HappinessComponent" }, "boosts": { "type": "boosts", "boosts": [ { "type": "att_boost_attacker", "value": 1, "targetedFeature": "all", "__class__": "BoostHint" }, { "type": "att_boost_attacker", "value": 2, "targetedFeature": "battleground", "__class__": "BoostHint" }, { "type": "def_boost_attacker", "value": 2, "targetedFeature": "all", "__class__": "BoostHint" }, { "type": "def_boost_attacker", "value": 2, "targetedFeature": "battleground", "__class__": "BoostHint" } ], "__class__": "BoostsComponent" } },
						"FutureEra": { "staticResources": { "type": "staticResources", "resources": { "resources": { "population": 520 }, "__class__": "Resources" }, "__class__": "StaticResourcesComponent" }, "happiness": { "type": "happiness", "demanded": 520, "__class__": "HappinessComponent" }, "boosts": { "type": "boosts", "boosts": [ { "type": "att_boost_attacker", "value": 1, "targetedFeature": "all", "__class__": "BoostHint" }, { "type": "att_boost_attacker", "value": 2, "targetedFeature": "battleground", "__class__": "BoostHint" }, { "type": "def_boost_attacker", "value": 2, "targetedFeature": "all", "__class__": "BoostHint" }, { "type": "def_boost_attacker", "value": 2, "targetedFeature": "battleground", "__class__": "BoostHint" } ], "__class__": "BoostsComponent" } },
						"ArcticFuture": { "staticResources": { "type": "staticResources", "resources": { "resources": { "population": 580 }, "__class__": "Resources" }, "__class__": "StaticResourcesComponent" }, "happiness": { "type": "happiness", "demanded": 580, "__class__": "HappinessComponent" }, "boosts": { "type": "boosts", "boosts": [ { "type": "att_boost_attacker", "value": 1, "targetedFeature": "all", "__class__": "BoostHint" }, { "type": "att_boost_attacker", "value": 2, "targetedFeature": "battleground", "__class__": "BoostHint" }, { "type": "def_boost_attacker", "value": 2, "targetedFeature": "all", "__class__": "BoostHint" }, { "type": "def_boost_attacker", "value": 2, "targetedFeature": "battleground", "__class__": "BoostHint" } ], "__class__": "BoostsComponent" } },
						"OceanicFuture": { "staticResources": { "type": "staticResources", "resources": { "resources": { "population": 640 }, "__class__": "Resources" }, "__class__": "StaticResourcesComponent" }, "happiness": { "type": "happiness", "demanded": 640, "__class__": "HappinessComponent" }, "boosts": { "type": "boosts", "boosts": [ { "type": "att_boost_attacker", "value": 1, "targetedFeature": "all", "__class__": "BoostHint" }, { "type": "att_boost_attacker", "value": 2, "targetedFeature": "battleground", "__class__": "BoostHint" }, { "type": "def_boost_attacker", "value": 2, "targetedFeature": "all", "__class__": "BoostHint" }, { "type": "def_boost_attacker", "value": 2, "targetedFeature": "battleground", "__class__": "BoostHint" } ], "__class__": "BoostsComponent" } },
						"VirtualFuture": { "staticResources": { "type": "staticResources", "resources": { "resources": { "population": 700 }, "__class__": "Resources" }, "__class__": "StaticResourcesComponent" }, "happiness": { "type": "happiness", "demanded": 700, "__class__": "HappinessComponent" }, "boosts": { "type": "boosts", "boosts": [ { "type": "att_boost_attacker", "value": 1, "targetedFeature": "all", "__class__": "BoostHint" }, { "type": "att_boost_attacker", "value": 2, "targetedFeature": "battleground", "__class__": "BoostHint" }, { "type": "def_boost_attacker", "value": 2, "targetedFeature": "all", "__class__": "BoostHint" }, { "type": "def_boost_attacker", "value": 2, "targetedFeature": "battleground", "__class__": "BoostHint" } ], "__class__": "BoostsComponent" } },
						"SpaceAgeMars": { "staticResources": { "type": "staticResources", "resources": { "resources": { "population": 1110 }, "__class__": "Resources" }, "__class__": "StaticResourcesComponent" }, "happiness": { "type": "happiness", "demanded": 1110, "__class__": "HappinessComponent" }, "boosts": { "type": "boosts", "boosts": [ { "type": "att_boost_attacker", "value": 1, "targetedFeature": "all", "__class__": "BoostHint" }, { "type": "att_boost_attacker", "value": 2, "targetedFeature": "battleground", "__class__": "BoostHint" }, { "type": "def_boost_attacker", "value": 2, "targetedFeature": "all", "__class__": "BoostHint" }, { "type": "def_boost_attacker", "value": 2, "targetedFeature": "battleground", "__class__": "BoostHint" } ], "__class__": "BoostsComponent" } },
						"SpaceAgeAsteroidBelt": { "staticResources": { "type": "staticResources", "resources": { "resources": { "population": 1200 }, "__class__": "Resources" }, "__class__": "StaticResourcesComponent" }, "happiness": { "type": "happiness", "demanded": 1200, "__class__": "HappinessComponent" }, "boosts": { "type": "boosts", "boosts": [ { "type": "att_boost_attacker", "value": 1, "targetedFeature": "all", "__class__": "BoostHint" }, { "type": "att_boost_attacker", "value": 2, "targetedFeature": "battleground", "__class__": "BoostHint" }, { "type": "def_boost_attacker", "value": 2, "targetedFeature": "all", "__class__": "BoostHint" }, { "type": "def_boost_attacker", "value": 2, "targetedFeature": "battleground", "__class__": "BoostHint" } ], "__class__": "BoostsComponent" } },
						"SpaceAgeVenus": { "staticResources": { "type": "staticResources", "resources": { "resources": { "population": 1300 }, "__class__": "Resources" }, "__class__": "StaticResourcesComponent" }, "happiness": { "type": "happiness", "demanded": 1300, "__class__": "HappinessComponent" }, "boosts": { "type": "boosts", "boosts": [ { "type": "att_boost_attacker", "value": 1, "targetedFeature": "all", "__class__": "BoostHint" }, { "type": "att_boost_attacker", "value": 2, "targetedFeature": "battleground", "__class__": "BoostHint" }, { "type": "def_boost_attacker", "value": 2, "targetedFeature": "all", "__class__": "BoostHint" }, { "type": "def_boost_attacker", "value": 2, "targetedFeature": "battleground", "__class__": "BoostHint" } ], "__class__": "BoostsComponent" } },
						"SpaceAgeJupiterMoon": { "staticResources": { "type": "staticResources", "resources": { "resources": { "population": 1400 }, "__class__": "Resources" }, "__class__": "StaticResourcesComponent" }, "happiness": { "type": "happiness", "demanded": 1400, "__class__": "HappinessComponent" }, "boosts": { "type": "boosts", "boosts": [ { "type": "att_boost_attacker", "value": 1, "targetedFeature": "all", "__class__": "BoostHint" }, { "type": "att_boost_attacker", "value": 2, "targetedFeature": "battleground", "__class__": "BoostHint" }, { "type": "def_boost_attacker", "value": 2, "targetedFeature": "all", "__class__": "BoostHint" }, { "type": "def_boost_attacker", "value": 2, "targetedFeature": "battleground", "__class__": "BoostHint" } ], "__class__": "BoostsComponent" } },
						"SpaceAgeTitan": { "staticResources": { "type": "staticResources", "resources": { "resources": { "population": 1500 }, "__class__": "Resources" }, "__class__": "StaticResourcesComponent" }, "happiness": { "type": "happiness", "demanded": 1500, "__class__": "HappinessComponent" }, "boosts": { "type": "boosts", "boosts": [ { "type": "att_boost_attacker", "value": 2, "targetedFeature": "all", "__class__": "BoostHint" }, { "type": "att_boost_attacker", "value": 2, "targetedFeature": "battleground", "__class__": "BoostHint" }, { "type": "def_boost_attacker", "value": 3, "targetedFeature": "all", "__class__": "BoostHint" }, { "type": "def_boost_attacker", "value": 2, "targetedFeature": "battleground", "__class__": "BoostHint" } ], "__class__": "BoostsComponent" } }
					},
					"stateDefinitionHash": "4ac9d4bce99479e33771a790a5df0494591e2288", "__class__": "GenericCityEntity", "type": "residential" 
				},
			};
			const oldCE = MainParser.CityEntities;
			MainParser.CityEntities = CityEntities;
			const buildings = { city_map: { entities: [
				{ "id": 123, "player_id": 123456, "cityentity_id": "W_MultiAge_WILD24G1", "type": "generic_building", "x": 8, "y": 15, "connected": 1,
					"state": { "next_state_transition_in": 2147483647, "next_state_transition_at": 2147483647, "constructionFinishedAt": 1703308494, "__class__": "ProducingState" },
					"level": 2, "__class__": "CityMapEntity"
				}
			]}};
			const member = { player_id: 123456, era: 'IronAge' };
			const oldGoodsData = GoodsData;
			GoodsData = [
				{ "id": "gems", "era": "IronAge", "abilities": { "goodsProduceable": {} } },
				{ "id": "cloth", "era": "IronAge", "abilities": { "goodsProduceable": {} } },
				{ "id": "lead", "era": "IronAge", "abilities": { "goodsProduceable": {} } },
				{ "id": "ebony", "era": "IronAge", "abilities": { "goodsProduceable": {} } },
				{ "id": "limestone", "era": "IronAge", "abilities": { "goodsProduceable": {} } }
			];
			const spy = spyOn(GuildMemberStat, 'UpdateData');

			await GuildMemberStat.ReadGuildMemberBuildings(buildings, member);

			expect(spy).toHaveBeenCalledWith('guildbuildings', { player_id: member.player_id, era: member.era, guildbuildings: [{
				gbid: 1, entity_id: 'W_MultiAge_WILD24G1', name: 'Blood Lilies', resources: { totalgoods: 5, goods: [
					{ "good_id": "cloth", "value": 1 }, { "good_id": "ebony", "value": 1 }, { "good_id": "gems", "value": 1 }, { "good_id": "lead", "value": 1 }, { "good_id": "limestone", "value": 1 }
				], onlywhenmotivated: true}, level: 3, era: 'IronAge'
			}], greatbuildings: [] });

			GoodsData = oldGoodsData;
			MainParser.CityEntities = oldCE;
		});
	});
});
